# Generated by Django 5.1.7 on 2025-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='live_index',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='live_index',
            name='img_about',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
