# Generated by Django 5.1.7 on 2025-04-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0002_alter_articel_body_alter_live_index_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_index',
            name='history_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='uploads/history/'),
        ),
        migrations.AddField(
            model_name='live_index',
            name='history_title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
