# Generated by Django 5.1.7 on 2025-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AddField(
            model_name='articel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
