# Generated by Django 5.1.7 on 2025-04-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0006_delete_contactmessage_articel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='uploads/aricels'),
        ),
    ]
