# Generated by Django 5.1.7 on 2025-04-05 20:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0007_articel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articel',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/aricels'),
        ),
    ]
