# Generated by Django 5.1.7 on 2025-04-05 20:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0008_alter_articel_body_alter_articel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
