# Generated by Django 5.1.7 on 2025-04-08 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
