# Generated by Django 5.1.7 on 2025-04-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0012_articel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articel',
            name='date',
        ),
    ]
