# Generated by Django 5.1.7 on 2025-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0014_articel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='puplic',
            field=models.CharField(default='پویا دلنواز', max_length=100),
        ),
    ]
