# Generated by Django 5.1.7 on 2025-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0015_articel_puplic'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='res_link',
            field=models.URLField(null=True),
        ),
    ]
