# Generated by Django 5.1.7 on 2025-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0016_articel_res_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articel',
            name='res_link',
        ),
        migrations.AddField(
            model_name='live_index',
            name='res_link',
            field=models.URLField(null=True),
        ),
    ]
