# Generated by Django 5.1.7 on 2025-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0017_remove_articel_res_link_live_index_res_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_index',
            name='instageram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='live_index',
            name='telgeram_link',
            field=models.URLField(null=True),
        ),
    ]
